name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flipping_card: ^0.0.3
  auto_size_text: ^2.1.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  flutter_launcher_name: ^0.0.1

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  timer_count_down: ^1.0.3
  firebase_database: ^3.1.6
  timer_builder: ^1.3.0
  flutter_timer: ^0.0.6
  firebase_messaging: ^6.0.16
  progress_dialog: ^1.2.4
  screen: ^0.0.5
  getflutter: ^1.0.11
  flutter_spinkit: ^4.1.2+1
  font_awesome_flutter: ^8.8.1
  dropdownfield: 1.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.jpg"
flutter_launcher_name:
  name: "NEORON"

flutter:
  uses-material-design: true

  assets:
  - images/
  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900
